qcd_hadronic_tau_selection = {
        "cr_d": {
                "tau": {
                        "tau_pt_threshold": 20,  
                        "tau_eta_threshold": 2.3, 
                        "tau_dz_threshold": 0.2, 
                        "tau_vs_jet": "Loose",
                        "tau_vs_ele": "Tight", 
                        "tau_vs_mu": "Tight",
                        "tau_vs_fail": "Tight",
                        "prongs": 13,     
                }, 
                "mu": {
                        "tau_pt_threshold": 20,  
                        "tau_eta_threshold": 2.3, 
                        "tau_dz_threshold": 0.2, 
                        "tau_vs_jet": "Tight",
                        "tau_vs_ele": "Tight", 
                        "tau_vs_mu": "Tight",
                        "tau_vs_fail": "Tight",
                        "prongs": 13,     
                }, 
                "ele": {
                        "tau_pt_threshold": 20,  
                        "tau_eta_threshold": 2.3, 
                        "tau_dz_threshold": 0.2, 
                        "tau_vs_jet": "Tight",
                        "tau_vs_ele": "Tight", 
                        "tau_vs_mu": "Tight",
                        "tau_vs_fail": "Tight",
                        "prongs": 13,     
                }, 
        },
        "cr_c": {
                "tau": {
                        "tau_pt_threshold": 20,  
                        "tau_eta_threshold": 2.3, 
                        "tau_dz_threshold": 0.2, 
                        "tau_vs_jet": "Tight",
                        "tau_vs_ele": "Tight", 
                        "tau_vs_mu": "Tight",
                        "tau_vs_fail": "Tight",
                        "prongs": 13,     
                }, 
                "mu": {
                        "tau_pt_threshold": 20,  
                        "tau_eta_threshold": 2.3, 
                        "tau_dz_threshold": 0.2, 
                        "tau_vs_jet": "Tight",
                        "tau_vs_ele": "Tight", 
                        "tau_vs_mu": "Tight",
                        "tau_vs_fail": "Tight",
                        "prongs": 13,     
                }, 
                "ele": {
                        "tau_pt_threshold": 20,  
                        "tau_eta_threshold": 2.3, 
                        "tau_dz_threshold": 0.2, 
                        "tau_vs_jet": "Tight",
                        "tau_vs_ele": "Tight", 
                        "tau_vs_mu": "Tight",
                        "tau_vs_fail": "Tight",
                        "prongs": 13,     
                }, 
        },    
        "cr_b": {
                "tau": {
                        "tau_pt_threshold": 20,  
                        "tau_eta_threshold": 2.3, 
                        "tau_dz_threshold": 0.2, 
                        "tau_vs_jet": "Loose",
                        "tau_vs_ele": "Tight", 
                        "tau_vs_mu": "Tight",
                        "tau_vs_fail": "Tight",
                        "prongs": 13,     
                }, 
                "mu": {
                        "tau_pt_threshold": 20,  
                        "tau_eta_threshold": 2.3, 
                        "tau_dz_threshold": 0.2, 
                        "tau_vs_jet": "Tight",
                        "tau_vs_ele": "Tight", 
                        "tau_vs_mu": "Tight",
                        "tau_vs_fail": "Tight",
                        "prongs": 13,     
                }, 
                "ele": {
                        "tau_pt_threshold": 20,  
                        "tau_eta_threshold": 2.3, 
                        "tau_dz_threshold": 0.2, 
                        "tau_vs_jet": "Tight",
                        "tau_vs_ele": "Tight", 
                        "tau_vs_mu": "Tight",
                        "tau_vs_fail": "Tight",
                        "prongs": 13,     
                }, 
        }
}