wjets_cases_selection = {
    "wjets":{
         "tau": {
            "case_1": True,  
            "case_2": True, 
            "case_3": True,
            "case_4": True,  
            "case_5": True, 
            "case_6": True,
            "case_7": True,  
            "case_8": True, 
            "case_9": True,
            "case_10": True,  
            "case_11": True, 
            "case_12": True,
            "case_13": True,
        },
         "mu": {
            "case_1": True,  
            "case_2": True, 
            "case_3": True,
            "case_4": True,  
            "case_5": True, 
            "case_6": True,
            "case_7": True,  
            "case_8": True, 
            "case_9": True,
            "case_10": True,  
            "case_11": True, 
            "case_12": True,
            "case_13": True,
        },
         "ele": {
            "case_1": True,  
            "case_2": True, 
            "case_3": True,
            "case_4": True,  
            "case_5": True, 
            "case_6": True,
            "case_7": True,  
            "case_8": True, 
            "case_9": True,
            "case_10": True,  
            "case_11": True, 
            "case_12": True,
            "case_13": True,
        },
    },
    "cr_b":{
         "tau": {
            "case_1": True,  
            "case_2": True, 
            "case_3": True,
            "case_4": True,  
            "case_5": True, 
            "case_6": True,
            "case_7": True,  
            "case_8": True, 
            "case_9": True,
            "case_10": True,  
            "case_11": True, 
            "case_12": True,
            "case_13": True,
        },
         "mu": {
            "case_1": True,  
            "case_2": True, 
            "case_3": True,
            "case_4": True,  
            "case_5": True, 
            "case_6": True,
            "case_7": True,  
            "case_8": True, 
            "case_9": True,
            "case_10": True,  
            "case_11": True, 
            "case_12": True,
            "case_13": True,
        },
         "ele": {
            "case_1": True,  
            "case_2": True, 
            "case_3": True,
            "case_4": True,  
            "case_5": True, 
            "case_6": True,
            "case_7": True,  
            "case_8": True, 
            "case_9": True,
            "case_10": True,  
            "case_11": True, 
            "case_12": True,
            "case_13": True,
        },
    },
    "cr_c":{
         "tau": {
            "case_1": True,  
            "case_2": True, 
            "case_3": True,
            "case_4": True,  
            "case_5": True, 
            "case_6": True,
            "case_7": True,  
            "case_8": True, 
            "case_9": True,
            "case_10": True,  
            "case_11": True, 
            "case_12": True,
            "case_13": True,
        },
         "mu": {
            "case_1": True,  
            "case_2": True, 
            "case_3": True,
            "case_4": True,  
            "case_5": True, 
            "case_6": True,
            "case_7": True,  
            "case_8": True, 
            "case_9": True,
            "case_10": True,  
            "case_11": True, 
            "case_12": True,
            "case_13": True,
        },
         "ele": {
            "case_1": True,  
            "case_2": True, 
            "case_3": True,
            "case_4": True,  
            "case_5": True, 
            "case_6": True,
            "case_7": True,  
            "case_8": True, 
            "case_9": True,
            "case_10": True,  
            "case_11": True, 
            "case_12": True,
            "case_13": True,
        },
    },
    "cr_d":{
         "tau": {
            "case_1": True,  
            "case_2": True, 
            "case_3": True,
            "case_4": True,  
            "case_5": True, 
            "case_6": True,
            "case_7": True,  
            "case_8": True, 
            "case_9": True,
            "case_10": True,  
            "case_11": True, 
            "case_12": True,
            "case_13": True,
        },
         "mu": {
            "case_1": True,  
            "case_2": True, 
            "case_3": True,
            "case_4": True,  
            "case_5": True, 
            "case_6": True,
            "case_7": True,  
            "case_8": True, 
            "case_9": True,
            "case_10": True,  
            "case_11": True, 
            "case_12": True,
            "case_13": True,
        },
         "ele": {
            "case_1": True,  
            "case_2": True, 
            "case_3": True,
            "case_4": True,  
            "case_5": True, 
            "case_6": True,
            "case_7": True,  
            "case_8": True, 
            "case_9": True,
            "case_10": True,  
            "case_11": True, 
            "case_12": True,
            "case_13": True,
        },
    },
}   

top_tagger_mW_mTop_Njets_selection = {
    "wjets":{
        "tau": {
            "m_W_min": 40.0,
            "m_W_max": 200.0,
            "m_Top_min": 100.0,
            "m_Top_max": 300.0,
        },
         "mu": {
            "m_W_min": 40.0,
            "m_W_max": 200.0,
            "m_Top_min": 100.0,
            "m_Top_max": 300.0,
        },
        "ele": {
            "m_W_min": 40.0,
            "m_W_max": 200.0,
            "m_Top_min": 100.0,
            "m_Top_max": 300.0,
        },
    },
    "cr_b":{
        "tau": {
            "m_W_min": 40.0,
            "m_W_max": 200.0,
            "m_Top_min": 100.0,
            "m_Top_max": 300.0,
        },
         "mu": {
            "m_W_min": 40.0,
            "m_W_max": 200.0,
            "m_Top_min": 100.0,
            "m_Top_max": 300.0,
        },
        "ele": {
            "m_W_min": 40.0,
            "m_W_max": 200.0,
            "m_Top_min": 100.0,
            "m_Top_max": 300.0,
        },
    },
    "cr_c":{
        "tau": {
            "m_W_min": 40.0,
            "m_W_max": 200.0,
            "m_Top_min": 100.0,
            "m_Top_max": 300.0,
        },
         "mu": {
            "m_W_min": 40.0,
            "m_W_max": 200.0,
            "m_Top_min": 100.0,
            "m_Top_max": 300.0,
        },
        "ele": {
            "m_W_min": 40.0,
            "m_W_max": 200.0,
            "m_Top_min": 100.0,
            "m_Top_max": 300.0,
        },
    },
    "cr_d":{
        "tau": {
            "m_W_min": 40.0,
            "m_W_max": 200.0,
            "m_Top_min": 100.0,
            "m_Top_max": 300.0,
        },
         "mu": {
            "m_W_min": 40.0,
            "m_W_max": 200.0,
            "m_Top_min": 100.0,
            "m_Top_max": 300.0,
        },
        "ele": {
            "m_W_min": 40.0,
            "m_W_max": 200.0,
            "m_Top_min": 100.0,
            "m_Top_max": 300.0,
        },
    }
}   